-- cli/commands/completions.lua
--
-- The `wez completions <zsh|bash>` subcommand (DIAG-05). The subcommand and its
-- `shell` argument are ALREADY registered in cli/spec.lua by Plan 01 — this module
-- ONLY implements the behavior; it does NOT edit the spec.
--
-- D-16 (single source of truth): the completion scripts are GENERATED by WALKING
-- the argparse parser built by cli/spec.lua. We enumerate every registered,
-- non-hidden subcommand and its flags and emit shell-appropriate completion
-- definitions. Because the walk reads the live spec, adding a subcommand to
-- spec.lua makes it appear in regenerated output with NO edit here — coverage
-- grows automatically per phase.
--
-- Dynamic values (future phases: colors, scene names) are NOT hardcoded. The
-- generated functions shell out to `wez __complete <context>` (cli/commands/
-- complete.lua) for any computed candidate set, so future contexts plug in by
-- teaching `__complete`, never by regenerating the static scripts.
--
-- Security (T-07-02): every value we splice into the generated scripts comes from
-- the closed spec command/flag set ([%w_-] tokens). We still treat the spec as the
-- only input and never interpolate raw user data into the emitted shell code.

local spec = require("cli.spec")

local M = {}

-- Subcommands that are internal hooks and MUST NOT be advertised as user-facing
-- completion candidates (they are still implemented commands, just hidden).
local HIDDEN = {
  ["__complete"] = true,
}

-- Walk a parser into a plain, shell-agnostic description of the command tree:
--   { commands = { { name=..., flags={ "--json", ... } }, ... } }
-- Only VISIBLE subcommands are included; the auto-added `-h/--help` option and any
-- short `-x` alias are dropped (we complete long flags). `names` (optional) is the
-- ordered/allow-listed subcommand list to honor; when omitted we use every command
-- the parser exposes. This is the single spec-walking step (D-16).
local function describe(parser, names)
  -- Map command name -> its argparse command object so we can read flags.
  local by_name = {}
  for _, cmd in ipairs(parser._commands or {}) do
    if cmd._name then by_name[cmd._name] = cmd end
  end

  -- The ordered visible name list: prefer the explicit `names`, else every
  -- parser command. Either way, drop hidden ones.
  local ordered = {}
  if names then
    for _, n in ipairs(names) do ordered[#ordered + 1] = n end
  else
    for _, cmd in ipairs(parser._commands or {}) do
      if cmd._name then ordered[#ordered + 1] = cmd._name end
    end
  end

  local commands = {}
  for _, name in ipairs(ordered) do
    if not HIDDEN[name] then
      local cmd = by_name[name]
      local flags = {}
      if cmd then
        for _, opt in ipairs(cmd._options or {}) do
          for _, alias in ipairs(opt._aliases or {}) do
            -- Keep long flags only, and never the auto help flag.
            if alias:match("^%-%-") and alias ~= "--help" then
              flags[#flags + 1] = alias
            end
          end
        end
      end
      commands[#commands + 1] = { name = name, flags = flags }
    end
  end
  return { commands = commands }
end

-- Build the default tree from the real spec (the production path). `names` is the
-- canonical allow-listed order from spec.subcommand_names() so output ordering is
-- stable and matches the dispatcher's allow-list.
local function describe_spec()
  return describe(spec.build_parser(), spec.subcommand_names())
end

-- Join a list of tokens with single spaces (used for candidate blocks).
local function words(list)
  return table.concat(list, " ")
end

-- ---------------------------------------------------------------------------
-- zsh generator
-- ---------------------------------------------------------------------------
-- Emits a `#compdef wez` function. Subcommand candidates live between explicit
-- WEZ_SUBCOMMANDS_BEGIN/END markers (so tests can assert the visible candidate
-- set precisely). Dynamic values route through `wez __complete`.
local function gen_zsh(tree)
  local subnames = {}
  for _, c in ipairs(tree.commands) do subnames[#subnames + 1] = c.name end

  local out = {}
  local function w(line) out[#out + 1] = line end

  w("#compdef wez")
  w("# Generated by `wez completions zsh` from cli/spec.lua (D-16). DO NOT EDIT BY HAND.")
  w("# Regenerate after the spec changes: `wez completions zsh > _wez`.")
  w("")
  w("_wez() {")
  w("  local -a _wez_subcommands")
  -- The visible subcommand candidate block, delimited so coverage is assertable.
  w("  # WEZ_SUBCOMMANDS_BEGIN")
  w("  _wez_subcommands=(" .. words(subnames) .. ")")
  w("  # WEZ_SUBCOMMANDS_END")
  w("")
  w("  local curcontext=\"$curcontext\" state line")
  w("  _arguments -C \\")
  w("    '1: :->subcmd' \\")
  w("    '*:: :->args'")
  w("")
  w("  case $state in")
  w("    subcmd)")
  -- Offer the static subcommand set AND any dynamic ones from `wez __complete`.
  w("      local -a _wez_dyn")
  w("      _wez_dyn=(${(f)\"$(wez __complete subcommands 2>/dev/null)\"})")
  w("      compadd -a _wez_subcommands")
  w("      compadd -a _wez_dyn")
  w("      ;;")
  w("    args)")
  w("      case $line[1] in")
  for _, c in ipairs(tree.commands) do
    -- `scene` has top-level flags AND subcommands (new/launch). Its generic flag
    -- arm is REPLACED by the hand-written nested scene) arm below (which dispatches
    -- launch -> scene-names, new -> flags), so SKIP it here to avoid a duplicate
    -- scene) case (ratified planner decision, Open Q3).
    if c.name ~= "scene" and #c.flags > 0 then
      w("        " .. c.name .. ")")
      w("          compadd " .. words(c.flags))
      w("          ;;")
    end
  end
  -- Nested dispatch for `pane` (its dynamic values come from `wez __complete`).
  -- pane has no top-level flags, so the generic flag loop emits no `pane)` arm —
  -- this is the single nested command in Phase 2.
  w("        pane)")
  w("          case $line[2] in")
  w("            color) compadd ${(f)\"$(wez __complete pane-colors 2>/dev/null)\"} ;;")
  w("            title) compadd ${(f)\"$(wez __complete pane-icons 2>/dev/null)\"} ;;")
  w("            *) compadd color title ;;")
  w("          esac")
  w("          ;;")
  -- Nested dispatch for `tab` — same shape as pane, routing to the tab-* contexts.
  w("        tab)")
  w("          case $line[2] in")
  w("            color) compadd ${(f)\"$(wez __complete tab-colors 2>/dev/null)\"} ;;")
  w("            title) compadd ${(f)\"$(wez __complete tab-icons 2>/dev/null)\"} ;;")
  w("            *) compadd color title ;;")
  w("          esac")
  w("          ;;")
  -- Nested dispatch for `scene` — REPLACES the generic flag arm (skipped in the
  -- loop above). Unlike pane/tab, scene has subcommands: launch <name> completes
  -- recipe names dynamically via `wez __complete scene-names` (SCEN-05/D-16, no
  -- hardcoded recipe names); new completes its tab-level flags; the bare scene
  -- word completes the subcommand names.
  w("        scene)")
  w("          case $line[2] in")
  w("            launch) compadd ${(f)\"$(wez __complete scene-names 2>/dev/null)\"} ;;")
  -- `new` completes FLAG NAMES, and the VALUE after --layout / --color routes to
  -- the dynamic contexts (D-16). ${words[CURRENT-1]} is the word before the cursor.
  w("            new)")
  w("              case \"${words[CURRENT-1]}\" in")
  w("                --layout) compadd ${(f)\"$(wez __complete scene-layouts 2>/dev/null)\"} ;;")
  w("                --color) compadd ${(f)\"$(wez __complete scene-colors 2>/dev/null)\"} ;;")
  w("                *) compadd --layout --pane --color --title ;;")
  w("              esac")
  w("              ;;")
  w("            *) compadd new launch ;;")
  w("          esac")
  w("          ;;")
  w("        *) ;;")
  w("      esac")
  w("      ;;")
  w("  esac")
  w("}")
  w("")
  w("_wez \"$@\"")
  return table.concat(out, "\n") .. "\n"
end

-- ---------------------------------------------------------------------------
-- bash generator
-- ---------------------------------------------------------------------------
-- Emits a bash function registered via `complete -F _wez wez`. Subcommand
-- candidates live between WEZ_SUBCOMMANDS_BEGIN/END markers. Dynamic values route
-- through `wez __complete`.
local function gen_bash(tree)
  local subnames = {}
  for _, c in ipairs(tree.commands) do subnames[#subnames + 1] = c.name end

  local out = {}
  local function w(line) out[#out + 1] = line end

  w("# bash completion for wez")
  w("# Generated by `wez completions bash` from cli/spec.lua (D-16). DO NOT EDIT BY HAND.")
  w("# Regenerate after the spec changes: `wez completions bash > wez.bash`.")
  w("")
  w("_wez() {")
  w("  local cur prev words cword")
  w("  COMPREPLY=()")
  w("  cur=\"${COMP_WORDS[COMP_CWORD]}\"")
  w("  prev=\"${COMP_WORDS[COMP_CWORD-1]}\"")
  w("")
  w("  # WEZ_SUBCOMMANDS_BEGIN")
  w("  local subcommands=\"" .. words(subnames) .. "\"")
  w("  # WEZ_SUBCOMMANDS_END")
  w("")
  w("  if [ \"$COMP_CWORD\" -eq 1 ]; then")
  -- Static set + dynamic candidates from `wez __complete`.
  w("    local dyn")
  w("    dyn=\"$(wez __complete subcommands 2>/dev/null)\"")
  w("    COMPREPLY=( $(compgen -W \"$subcommands $dyn\" -- \"$cur\") )")
  w("    return 0")
  w("  fi")
  w("")
  w("  local cmd=\"${COMP_WORDS[1]}\"")
  w("  case \"$cmd\" in")
  for _, c in ipairs(tree.commands) do
    -- Skip `scene` here: its generic flag arm is REPLACED by the hand-written
    -- nested scene) arm below (launch -> scene-names, new -> flags). See zsh path.
    if c.name ~= "scene" and #c.flags > 0 then
      w("    " .. c.name .. ")")
      w("      COMPREPLY=( $(compgen -W \"" .. words(c.flags) .. "\" -- \"$cur\") )")
      w("      return 0")
      w("      ;;")
    end
  end
  -- Nested dispatch for `pane` (dynamic values via `wez __complete`).
  w("    pane)")
  w("      local sub=\"${COMP_WORDS[2]}\"")
  w("      case \"$sub\" in")
  w("        color) COMPREPLY=( $(compgen -W \"$(wez __complete pane-colors 2>/dev/null)\" -- \"$cur\") ); return 0 ;;")
  w("        title) COMPREPLY=( $(compgen -W \"$(wez __complete pane-icons 2>/dev/null)\" -- \"$cur\") ); return 0 ;;")
  w("        *) COMPREPLY=( $(compgen -W \"color title\" -- \"$cur\") ); return 0 ;;")
  w("      esac")
  w("      ;;")
  -- Nested dispatch for `tab` — same shape as pane, routing to the tab-* contexts.
  w("    tab)")
  w("      local sub=\"${COMP_WORDS[2]}\"")
  w("      case \"$sub\" in")
  w("        color) COMPREPLY=( $(compgen -W \"$(wez __complete tab-colors 2>/dev/null)\" -- \"$cur\") ); return 0 ;;")
  w("        title) COMPREPLY=( $(compgen -W \"$(wez __complete tab-icons 2>/dev/null)\" -- \"$cur\") ); return 0 ;;")
  w("        *) COMPREPLY=( $(compgen -W \"color title\" -- \"$cur\") ); return 0 ;;")
  w("      esac")
  w("      ;;")
  -- Nested dispatch for `scene` — REPLACES the generic flag arm (skipped above).
  -- launch <name> completes recipe names dynamically via scene-names (SCEN-05/
  -- D-16, no hardcoded recipe names); new completes its flags; bare scene
  -- completes the subcommand names.
  w("    scene)")
  w("      local sub=\"${COMP_WORDS[2]}\"")
  w("      case \"$sub\" in")
  w("        launch) COMPREPLY=( $(compgen -W \"$(wez __complete scene-names 2>/dev/null)\" -- \"$cur\") ); return 0 ;;")
  -- `new` completes FLAG NAMES; the VALUE after --layout / --color routes to the
  -- dynamic contexts (D-16). $prev is the word before the cursor (set at top).
  w("        new)")
  w("          case \"$prev\" in")
  w("            --layout) COMPREPLY=( $(compgen -W \"$(wez __complete scene-layouts 2>/dev/null)\" -- \"$cur\") ); return 0 ;;")
  w("            --color) COMPREPLY=( $(compgen -W \"$(wez __complete scene-colors 2>/dev/null)\" -- \"$cur\") ); return 0 ;;")
  w("            *) COMPREPLY=( $(compgen -W \"--layout --pane --color --title\" -- \"$cur\") ); return 0 ;;")
  w("          esac")
  w("          ;;")
  w("        *) COMPREPLY=( $(compgen -W \"new launch\" -- \"$cur\") ); return 0 ;;")
  w("      esac")
  w("      ;;")
  w("    *) ;;")
  w("  esac")
  w("}")
  w("")
  w("complete -F _wez wez")
  return table.concat(out, "\n") .. "\n"
end

-- run(args): generate the completion script for args.shell ('zsh'|'bash') and
-- print it to stdout. For testability, args may optionally carry an explicit
-- `parser` and `names` to drive the walk off an arbitrary spec; production passes
-- neither and the real cli/spec.lua is walked.
function M.run(args)
  args = args or {}
  local shell = args.shell

  if type(shell) ~= "string" or shell == "" then
    io.stderr:write("wez completions: a shell is required (zsh|bash)\n")
    return 2
  end

  local tree
  if args.parser then
    tree = describe(args.parser, args.names)
  else
    tree = describe_spec()
  end

  if shell == "zsh" then
    io.write(gen_zsh(tree))
    return 0
  elseif shell == "bash" then
    io.write(gen_bash(tree))
    return 0
  end

  io.stderr:write(("wez completions: unsupported shell '%s' (want zsh|bash)\n"):format(shell))
  return 2
end

return M
